from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Institution)
admin.site.register(User)
admin.site.register(Profile)
admin.site.register(AcademicYear)
admin.site.register(Term)
admin.site.register(Department)
admin.site.register(Program)
admin.site.register(Course)
admin.site.register(CourseRun)
admin.site.register(Enrollment)
admin.site.register(Module)
admin.site.register(Lesson)
admin.site.register(Content)
admin.site.register(Assignment)
admin.site.register(Quiz)
admin.site.register(Question)
admin.site.register(Choice)
admin.site.register(Submission)
admin.site.register(Grade)
admin.site.register(Announcement)
admin.site.register(Discussion)
admin.site.register(Payment)
admin.site.register(Attendance)
